// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadFlakyNetwork returns the embedded CollectionSpec for flakyNetwork.
func loadFlakyNetwork() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlakyNetworkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flakyNetwork: %w", err)
	}

	return spec, err
}

// loadFlakyNetworkObjects loads flakyNetwork and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flakyNetworkObjects
//	*flakyNetworkPrograms
//	*flakyNetworkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlakyNetworkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlakyNetwork()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flakyNetworkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flakyNetworkSpecs struct {
	flakyNetworkProgramSpecs
	flakyNetworkMapSpecs
	flakyNetworkVariableSpecs
}

// flakyNetworkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flakyNetworkProgramSpecs struct {
	FlakyNetworkRecvfrom  *ebpf.ProgramSpec `ebpf:"flaky_network_recvfrom"`
	FlakyNetworkRecvmsg   *ebpf.ProgramSpec `ebpf:"flaky_network_recvmsg"`
	FlakyNetworkTrackExit *ebpf.ProgramSpec `ebpf:"flaky_network_track_exit"`
	FlakyNetworkTrackFork *ebpf.ProgramSpec `ebpf:"flaky_network_track_fork"`
}

// flakyNetworkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flakyNetworkMapSpecs struct {
	FaultConfig *ebpf.MapSpec `ebpf:"fault_config"`
	FaultCount  *ebpf.MapSpec `ebpf:"fault_count"`
}

// flakyNetworkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flakyNetworkVariableSpecs struct {
}

// flakyNetworkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlakyNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type flakyNetworkObjects struct {
	flakyNetworkPrograms
	flakyNetworkMaps
	flakyNetworkVariables
}

func (o *flakyNetworkObjects) Close() error {
	return _FlakyNetworkClose(
		&o.flakyNetworkPrograms,
		&o.flakyNetworkMaps,
	)
}

// flakyNetworkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlakyNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type flakyNetworkMaps struct {
	FaultConfig *ebpf.Map `ebpf:"fault_config"`
	FaultCount  *ebpf.Map `ebpf:"fault_count"`
}

func (m *flakyNetworkMaps) Close() error {
	return _FlakyNetworkClose(
		m.FaultConfig,
		m.FaultCount,
	)
}

// flakyNetworkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFlakyNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type flakyNetworkVariables struct {
}

// flakyNetworkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlakyNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type flakyNetworkPrograms struct {
	FlakyNetworkRecvfrom  *ebpf.Program `ebpf:"flaky_network_recvfrom"`
	FlakyNetworkRecvmsg   *ebpf.Program `ebpf:"flaky_network_recvmsg"`
	FlakyNetworkTrackExit *ebpf.Program `ebpf:"flaky_network_track_exit"`
	FlakyNetworkTrackFork *ebpf.Program `ebpf:"flaky_network_track_fork"`
}

func (p *flakyNetworkPrograms) Close() error {
	return _FlakyNetworkClose(
		p.FlakyNetworkRecvfrom,
		p.FlakyNetworkRecvmsg,
		p.FlakyNetworkTrackExit,
		p.FlakyNetworkTrackFork,
	)
}

func _FlakyNetworkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flakynetwork_bpfel.o
var _FlakyNetworkBytes []byte
