// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadToolPermDenied returns the embedded CollectionSpec for toolPermDenied.
func loadToolPermDenied() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ToolPermDeniedBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load toolPermDenied: %w", err)
	}

	return spec, err
}

// loadToolPermDeniedObjects loads toolPermDenied and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*toolPermDeniedObjects
//	*toolPermDeniedPrograms
//	*toolPermDeniedMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadToolPermDeniedObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadToolPermDenied()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// toolPermDeniedSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type toolPermDeniedSpecs struct {
	toolPermDeniedProgramSpecs
	toolPermDeniedMapSpecs
	toolPermDeniedVariableSpecs
}

// toolPermDeniedProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type toolPermDeniedProgramSpecs struct {
	ToolPermDeniedOpenat    *ebpf.ProgramSpec `ebpf:"tool_perm_denied_openat"`
	ToolPermDeniedTrackExit *ebpf.ProgramSpec `ebpf:"tool_perm_denied_track_exit"`
	ToolPermDeniedTrackFork *ebpf.ProgramSpec `ebpf:"tool_perm_denied_track_fork"`
}

// toolPermDeniedMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type toolPermDeniedMapSpecs struct {
	FaultConfig *ebpf.MapSpec `ebpf:"fault_config"`
	FaultEvents *ebpf.MapSpec `ebpf:"fault_events"`
}

// toolPermDeniedVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type toolPermDeniedVariableSpecs struct {
}

// toolPermDeniedObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadToolPermDeniedObjects or ebpf.CollectionSpec.LoadAndAssign.
type toolPermDeniedObjects struct {
	toolPermDeniedPrograms
	toolPermDeniedMaps
	toolPermDeniedVariables
}

func (o *toolPermDeniedObjects) Close() error {
	return _ToolPermDeniedClose(
		&o.toolPermDeniedPrograms,
		&o.toolPermDeniedMaps,
	)
}

// toolPermDeniedMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadToolPermDeniedObjects or ebpf.CollectionSpec.LoadAndAssign.
type toolPermDeniedMaps struct {
	FaultConfig *ebpf.Map `ebpf:"fault_config"`
	FaultEvents *ebpf.Map `ebpf:"fault_events"`
}

func (m *toolPermDeniedMaps) Close() error {
	return _ToolPermDeniedClose(
		m.FaultConfig,
		m.FaultEvents,
	)
}

// toolPermDeniedVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadToolPermDeniedObjects or ebpf.CollectionSpec.LoadAndAssign.
type toolPermDeniedVariables struct {
}

// toolPermDeniedPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadToolPermDeniedObjects or ebpf.CollectionSpec.LoadAndAssign.
type toolPermDeniedPrograms struct {
	ToolPermDeniedOpenat    *ebpf.Program `ebpf:"tool_perm_denied_openat"`
	ToolPermDeniedTrackExit *ebpf.Program `ebpf:"tool_perm_denied_track_exit"`
	ToolPermDeniedTrackFork *ebpf.Program `ebpf:"tool_perm_denied_track_fork"`
}

func (p *toolPermDeniedPrograms) Close() error {
	return _ToolPermDeniedClose(
		p.ToolPermDeniedOpenat,
		p.ToolPermDeniedTrackExit,
		p.ToolPermDeniedTrackFork,
	)
}

func _ToolPermDeniedClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed toolpermdenied_bpfel.o
var _ToolPermDeniedBytes []byte
